version: 2.1
jobs:
  build_test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
  build_docker_image:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: |
            docker build -t nodejswebapp1 -t bittusharma9534/nodejswebapp1:latest .
            # echo "$DOCKER_PASSWORD" | docker login -u bittusharma9534 --password-stdu
            # docker push bittusharma9534/nodejswebapp1:latest

workflows:
  version: 2.1
  build_test:
    jobs:
      - build_test
      - build_docker_image
